version: '3.1'
services:
 mysql:
  image: mysql
  container_name: mysql
  volumes:
    - /home/isaac/PycharmProjects/recommender_system_nerds/data:/data
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=secret

  ports:
    - "3306:3306"